# Generated by Django 3.2 on 2021-08-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_message',
            name='dataURL',
            field=models.CharField(default='', max_length=100000000),
            preserve_default=False,
        ),
    ]
