# Generated by Django 3.2 on 2021-08-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
    ]
